<a href="https://colab.research.google.com/github/mimomaina/pythondataanalysis/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

In [2]:
import numpy as np

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
array = np.ones((3, 3))
bordered_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)
print(bordered_array)


[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)               # nan
print(np.nan == np.nan)         # False
print(np.inf > np.nan)          # False
print(np.nan - np.nan)          # nan
print(np.nan in set([np.nan]))  # True
print(0.3 == 3 * 0.1)           # False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [5]:
matrix = np.diag(np.arange(1, 5), k=-1)
print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [6]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [7]:
index = np.unravel_index(99, (6, 7, 8))
print(index)


(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [8]:
pattern = np.array([[0, 1], [1, 0]])
checkerboard = np.tile(pattern, (4, 4))
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [9]:
random_matrix = np.random.random((5, 5))
normalized_matrix = (random_matrix - random_matrix.min()) / (random_matrix.max() - random_matrix.min())
print(normalized_matrix)


[[0.62502509 0.09740919 0.27391734 0.71655114 0.1042616 ]
 [0.80283067 0.         0.41179308 0.63025112 0.63601458]
 [0.17296643 0.58968855 0.49995947 0.7131128  1.        ]
 [0.37747341 0.0082225  0.51623474 0.11238024 0.60086494]
 [0.41627002 0.18837501 0.25428594 0.39256732 0.02429801]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [10]:
color_dtype = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])
print(color_dtype)


[('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [11]:
A = np.random.random((5, 3))
B = np.random.random((3, 2))
product = np.dot(A, B)
print(product)


[[0.29796254 0.13136644]
 [0.78030569 0.48796802]
 [1.27639304 0.71578909]
 [0.6855334  0.50158935]
 [0.79659991 0.5561725 ]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [12]:
array = np.arange(10)
array[(array > 3) & (array < 8)] *= -1
print(array)


[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
# Author: Jake VanderPlas
print(sum(range(5), -1))  # Output: 9 (sum of range(5) = 10, then adding -1)
from numpy import *
print(sum(range(5), -1))  # Output: 10 (NumPy sum treats -1 as the axis parameter, summing over axis -1)


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(5)
# Legal:
print(Z**Z)      # Raises each element to the power of itself
print(2 << Z >> 2)  # Bitwise operations
print(Z <- Z)    # Boolean comparison
print(1j * Z)    # Complex number multiplication
print(Z / 1 / 1) # Division works
# Illegal:
# print(Z<Z>Z)   # Chained comparison is not supported


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))   # RuntimeWarning, result: nan
print(np.array(0) // np.array(0))  # RuntimeWarning, result: 0 (integer division)
print(np.array([np.nan]).astype(int).astype(float))  # Result: [-9.22337204e+18] (system-dependent)


#### 29. How to round away from zero a float array ? (★☆☆)

In [13]:
float_array = np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7])
rounded = np.copysign(np.ceil(np.abs(float_array)), float_array)
print(rounded)


[-2. -2. -1.  1.  2.  2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [14]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])
common_values = np.intersect1d(array1, array2)
print(common_values)


[4 5]
