<a href="https://colab.research.google.com/github/mimomaina/pythondataanalysis/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Exercise 3

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [2]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')
# Example
np.seterr(all='ignore')
print(np.sqrt(-1))


nan


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [3]:
print(np.sqrt(-1) == np.emath.sqrt(-1))  # False
# `np.sqrt` returns NaN for negative numbers, while `np.emath.sqrt` handles complex numbers.


False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [4]:
today = np.datetime64('today', 'D')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')
print(f"Yesterday: {yesterday}, Today: {today}, Tomorrow: {tomorrow}")


Yesterday: 2024-11-18, Today: 2024-11-19, Tomorrow: 2024-11-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [5]:
july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(july_2016)


['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [6]:
A = np.ones(5)
B = np.ones(5) * 2
np.add(A, B, out=A)        # A = A + B
np.divide(A, -2, out=A)    # A = -A/2
print(A)


[-1.5 -1.5 -1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [7]:
array = np.random.uniform(0, 10, 10)
print(array.astype(int))          # Method 1
print(np.floor(array))            # Method 2
print(np.trunc(array))            # Method 3
print(array // 1)                 # Method 4


[8 6 8 7 3 4 8 8 6 1]
[8. 6. 8. 7. 3. 4. 8. 8. 6. 1.]
[8. 6. 8. 7. 3. 4. 8. 8. 6. 1.]
[8. 6. 8. 7. 3. 4. 8. 8. 6. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [9]:
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [10]:
def generate():
    for i in range(10):
        yield i

array = np.fromiter(generate(), dtype=int)
print(array)


[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [11]:
vector = np.linspace(0, 1, 12)[1:-1]
print(vector)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [12]:
vector = np.random.random(10)
vector.sort()
print(vector)


[0.10813325 0.11464354 0.25597379 0.2568798  0.27207987 0.34694496
 0.3471146  0.39557961 0.93305044 0.97803854]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [13]:
array = np.arange(10)
result = np.add.reduce(array)
print(result)


45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [14]:
A = np.random.random(10)
B = np.random.random(10)
are_equal = np.array_equal(A, B)
print(are_equal)


False


#### 43. Make an array immutable (read-only) (★★☆)

In [15]:
array = np.ones(10)
array.flags.writeable = False
print(array)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [16]:
cartesian = np.random.random((10, 2))
x, y = cartesian[:, 0], cartesian[:, 1]
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
polar = np.column_stack((r, theta))
print(polar)


[[0.97164178 1.31511005]
 [0.94472588 1.10381858]
 [0.96797073 1.16437234]
 [0.54585808 1.33908673]
 [0.7910242  1.42126336]
 [0.37698604 0.5039771 ]
 [1.10300077 0.65082274]
 [1.01561706 0.35352878]
 [0.8819971  0.63630778]
 [0.4491202  1.45527035]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [17]:
vector = np.random.random(10)
vector[vector.argmax()] = 0
print(vector)


[0.63075621 0.1981903  0.66253167 0.42495535 0.46387229 0.80907935
 0.49552979 0.64539193 0.         0.16762754]
